version: '3.8'
services:
  web:
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"
